### ISSUE TITLE
Colaboradores

### ISSUE THREAD

**Issue by anuar-FP** [anuar-FP/HolaMundoAnouarBettahiBerdai#1]
[https://github.com/anuar-FP/HolaMundoAnouarBettahiBerdai](url)
@jorgermasir @rafaeldiazmata @Borja-Benegas

**Comment by Andres-Heras** [comment]
Te falta cerrar la tabla

**Comment by anuar-FP** [comment]
que tabla?

**Comment by Andres-Heras** [comment]
La etiqueta </table>, no?

**Comment by anuar-FP** [comment]
que va yo creo que no de echo yo pego esto siempre:
<tr>
<td>Anouar Bettahi Berdai</td>
<td>anuar-fp</td>
<td><a href="https://anuar-fp.github.io/HolaMundoAnouarBettahiBerdai/">
https://anuar-fp.github.io/HolaMundoAnouarBettahiBerdai/</a></td>
<td><a href="https://github.com/anuar-FP/HolaMundoAnouarBettahiBerdai">
https://github.com/anuar-FP/HolaMundoAnouarBettahiBerdai</a></td>
</tr>
